apiVersion: v1
kind: Pod
metadata:
  name: fedora
  namespace: default
spec:
  containers:
  - name: fedora
    image: fedora
    command: [/bin/bash]
    args: ["-c", "while true; do sleep 10; done"]
    volumeMounts:
    - name: r00
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: r00
    flexVolume:
      driver: "linbit/linstor-flexvolume"
      fsType: "ext4"
      options:
        resource: "r00"

