apiVersion: v1
kind: Pod
metadata:
  name: fedora
  namespace: default
spec:
  containers:
  - name: fedora
    image: fedora
    command: [/bin/bash]
    args: ["-c", "while true; do sleep 10; done"]
    volumeMounts:
    - name: r0
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: r0
    flexVolume:
      driver: "linbit/linstor-flexvolume"
      fsType: "xfs"
      options:
        resource: "r0"
        blockSize: "4096"
        force: "true"
        xfsDiscardBlocks: "true"
        xfsDataSu: "128k"
        xfsDataSw: "1"
        xfsLogDev: "/tmp/example"
        controllers: "192.168.100.100:3367"

